server:
    port: 8081
spring:
    application:
        name: WorkersApplication
    datasource:
        url: jdbc:mysql://localhost:3306/workerData
        username: root
        password: mysql
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
        show-sql: true

        